# Generated by Django 3.1.5 on 2021-01-22 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='columnHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=40)),
                ('column_sort', models.IntegerField(default=0)),
                ('column_Header', models.CharField(max_length=40)),
                ('column_Lable', models.CharField(default='Column Header', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='company_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_Name', models.CharField(max_length=210)),
                ('Estblish_Date', models.DateField(default='1900-01-01')),
                ('city', models.CharField(default='', max_length=80)),
                ('state', models.CharField(default='', max_length=80)),
                ('country', models.CharField(default='', max_length=80)),
                ('zipcode', models.CharField(default='', max_length=8)),
                ('GSTIN', models.CharField(default='', max_length=40)),
                ('CSTIN', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='content_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='product_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_Name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='product_Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_Name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Tax_Master',
            fields=[
                ('Tax_name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('Tax_percetage', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='UOM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UOM_Code', models.CharField(max_length=3)),
                ('UOM_Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tax_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tax_GrpCd', models.CharField(default='', max_length=3)),
                ('Tax_Group', models.CharField(max_length=40)),
                ('Tax_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.tax_master')),
            ],
        ),
        migrations.CreateModel(
            name='product_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Code', models.CharField(default='', max_length=12)),
                ('product_Name', models.CharField(default='', max_length=80)),
                ('product_SName', models.CharField(default='', max_length=30)),
                ('product_Barcode', models.CharField(default='', max_length=20)),
                ('product_VendRef', models.CharField(default='', max_length=30)),
                ('product_GSTName', models.CharField(default='', max_length=30)),
                ('product_GSTUnit', models.CharField(default='', max_length=20)),
                ('product_Schedule', models.CharField(default='', max_length=20)),
                ('product_HSNCode', models.CharField(default='', max_length=20)),
                ('product_Class', models.CharField(default='', max_length=20)),
                ('product_Pack', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('product_MfgBy', models.CharField(default='', max_length=40)),
                ('product_MktBy', models.CharField(default='', max_length=80)),
                ('product_Division', models.CharField(default='', max_length=40)),
                ('product_PuRate', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('product_SaleRate', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('product_MRP', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('product_Discount', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
                ('product_STaxGrp', models.CharField(default='', max_length=3)),
                ('product_PTaxGrp', models.CharField(default='', max_length=3)),
                ('product_MinStk', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('product_MaxStk', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('product_MinOrd', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('Product_Location', models.CharField(default='', max_length=20)),
                ('product_BUOM', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pharmacy.uom')),
                ('product_Category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pharmacy.product_category')),
                ('product_Content', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pharmacy.content_master')),
                ('product_SubCat', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pharmacy.product_subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='product_Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Batch', models.CharField(max_length=20)),
                ('product_PuRate', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('product_SaleRate', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('product_MRP', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('product_MfgDate', models.DateField()),
                ('product_ExpDate', models.DateField()),
                ('product_Discount', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
                ('product_OPStock', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('product_OPRate', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('product_CLStock', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.product_master')),
                ('product_UOM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.uom')),
            ],
        ),
        migrations.CreateModel(
            name='product_AUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_BQty', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('product_Factor', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.product_master')),
                ('product_AUOM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.uom')),
            ],
        ),
    ]
